remove all_reduce check

diff --git a/.github/workflows/ixuca-smoke-schedule.yml b/.github/workflows/ixuca-smoke-schedule.yml
--- a/.github/workflows/ixuca-smoke-schedule.yml
+++ b/.github/workflows/ixuca-smoke-schedule.yml
@@ -3,7 +3,7 @@ name: IXUCA-Smoke-Schedule
 on:
   workflow_dispatch:
   schedule:
-    - cron: "*/20 * * * *"
+    - cron: "*/30 * * * *"
 
 permissions: read-all
 
@@ -72,14 +72,14 @@ jobs:
             echo "GPU count is <= 1, card status is abnormal."
             exit 1
           fi
-          toolbox_bin=$(ls -d /usr/local/corex/corex-toolbox-*/bin 2>/dev/null | head -n 1)
-          if [ -z "${toolbox_bin}" ]; then
-            echo "Cannot find /usr/local/corex/corex-toolbox-*/bin"
-            exit 1
-          fi
-          cd "${toolbox_bin}"
-          mpirun --allow-run-as-root --report-bindings -tag-output --prefix /usr/local -np 2 --bind-to none --map-by node -mca btl ^openib ./all_reduce_perf -b 8 -e 1G -f 2 -g 1
-          cd -
+          # toolbox_bin=$(ls -d /usr/local/corex/corex-toolbox-*/bin 2>/dev/null | head -n 1)
+          # if [ -z "${toolbox_bin}" ]; then
+          #   echo "Cannot find /usr/local/corex/corex-toolbox-*/bin"
+          #   exit 1
+          # fi
+          # cd "${toolbox_bin}"
+          # mpirun --allow-run-as-root --report-bindings -tag-output --prefix /usr/local -np 2 --bind-to none --map-by node -mca btl ^openib ./all_reduce_perf -b 8 -e 1G -f 2 -g 1
+          # cd -
           python3 - <<'PY'
           import paddle
           paddle.utils.run_check()
