fix perf

diff --git a/.github/workflows/ixuca-smoke-schedule.yml b/.github/workflows/ixuca-smoke-schedule.yml
--- a/.github/workflows/ixuca-smoke-schedule.yml
+++ b/.github/workflows/ixuca-smoke-schedule.yml
@@ -72,14 +72,15 @@ jobs:
             echo "GPU count is <= 1, card status is abnormal."
             exit 1
           fi
-          # toolbox_bin=$(ls -d /usr/local/corex/corex-toolbox-*/bin 2>/dev/null | head -n 1)
-          # if [ -z "${toolbox_bin}" ]; then
-          #   echo "Cannot find /usr/local/corex/corex-toolbox-*/bin"
-          #   exit 1
-          # fi
-          # cd "${toolbox_bin}"
-          # mpirun --allow-run-as-root --report-bindings -tag-output --prefix /usr/local -np 2 --bind-to none --map-by node -mca btl ^openib ./all_reduce_perf -b 8 -e 1G -f 2 -g 1
-          # cd -
+          export LD_LIBRARY_PATH=/usr/local/openmpi/lib/:$LD_LIBRARY_PATH
+          toolbox_bin=$(ls -d /usr/local/corex/corex-toolbox-*/bin 2>/dev/null | head -n 1)
+          if [ -z "${toolbox_bin}" ]; then
+            echo "Cannot find /usr/local/corex/corex-toolbox-*/bin"
+            exit 1
+          fi
+          cd "${toolbox_bin}"
+          mpirun --allow-run-as-root --report-bindings -tag-output --prefix /usr/local -np 2 --bind-to none --map-by node -mca btl ^openib ./all_reduce_perf -b 8 -e 1G -f 2 -g 1
+          cd -
           python3 - <<'PY'
           import paddle
           paddle.utils.run_check()
